/**
 * All SmartERP keyboard shortcuts.
 * Each entry: { id, key, ctrl, alt, shift, label, description, group }
 * 'action' is injected at the component level.
 */

export const SHORTCUT_GROUPS = {
  GLOBAL: "Global",
  MASTERS: "Masters",
  VOUCHERS: "Vouchers",
  INVENTORY: "Inventory",
  BILLING: "Billing",
  CUSTOMER: "Customer",
  SUPPLIER: "Supplier",
  REPORTS: "Reports",
  NAVIGATE: "Navigation",
};

export const SHORTCUTS = [
  // ── Global ──────────────────────────────────────────────────────
  {
    id: "company_select",
    key: "F1",
    label: "F1",
    description: "Company Selection",
    group: "GLOBAL",
  },
  {
    id: "change_fy",
    key: "F2",
    label: "F2",
    description: "Change Financial Year",
    group: "GLOBAL",
  },
  {
    id: "company_info",
    key: "F3",
    label: "F3",
    description: "Company Info",
    group: "GLOBAL",
  },
  {
    id: "calculator",
    key: "F4",
    label: "F4",
    description: "Calculator",
    group: "GLOBAL",
  },
  {
    id: "refresh",
    key: "F5",
    label: "F5",
    description: "Refresh",
    group: "GLOBAL",
  },
  {
    id: "escape",
    key: "Escape",
    label: "Esc",
    description: "Previous Screen / Close",
    group: "GLOBAL",
  },
  {
    id: "logout",
    key: "q",
    ctrl: true,
    label: "Ctrl+Q",
    description: "Logout",
    group: "GLOBAL",
  },
  {
    id: "home",
    key: "h",
    ctrl: true,
    label: "Ctrl+H",
    description: "Go Home",
    group: "GLOBAL",
  },
  {
    id: "command_search",
    key: "k",
    ctrl: true,
    label: "Ctrl+K",
    description: "Command Search",
    group: "GLOBAL",
  },
  {
    id: "shortcut_help",
    key: "?",
    label: "?",
    description: "Show all shortcuts",
    group: "GLOBAL",
  },

  // ── Masters ──────────────────────────────────────────────────────
  {
    id: "create_ledger",
    key: "l",
    alt: true,
    label: "Alt+L",
    description: "Create Ledger",
    group: "MASTERS",
  },
  {
    id: "alter_ledger",
    key: "a",
    alt: true,
    label: "Alt+A",
    description: "Alter Ledger",
    group: "MASTERS",
  },
  {
    id: "create_group",
    key: "g",
    alt: true,
    label: "Alt+G",
    description: "Create Group",
    group: "MASTERS",
  },
  {
    id: "create_stock",
    key: "s",
    alt: true,
    label: "Alt+S",
    description: "Create Stock Item",
    group: "MASTERS",
  },
  {
    id: "create_unit",
    key: "u",
    alt: true,
    label: "Alt+U",
    description: "Create Unit",
    group: "MASTERS",
  },

  // ── Vouchers ─────────────────────────────────────────────────────
  {
    id: "receipt_voucher",
    key: "F6",
    label: "F6",
    description: "Receipt Voucher",
    group: "VOUCHERS",
  },
  {
    id: "journal_voucher",
    key: "F7",
    label: "F7",
    description: "Journal Voucher",
    group: "VOUCHERS",
  },
  {
    id: "sales_voucher",
    key: "F8",
    label: "F8",
    description: "Sales Voucher",
    group: "VOUCHERS",
  },
  {
    id: "purchase_voucher",
    key: "F9",
    label: "F9",
    description: "Purchase Voucher",
    group: "VOUCHERS",
  },
  {
    id: "rev_journal",
    key: "F10",
    label: "F10",
    description: "Reversing Journal",
    group: "VOUCHERS",
  },
  {
    id: "credit_note",
    key: "F8",
    alt: true,
    label: "Alt+F8",
    description: "Credit Note",
    group: "VOUCHERS",
  },
  {
    id: "debit_note",
    key: "F9",
    alt: true,
    label: "Alt+F9",
    description: "Debit Note",
    group: "VOUCHERS",
  },
  {
    id: "payment_voucher",
    key: "F5",
    alt: true,
    label: "Alt+F5",
    description: "Payment Voucher",
    group: "VOUCHERS",
  },

  // ── Inventory ────────────────────────────────────────────────────
  {
    id: "inventory_dash",
    key: "i",
    ctrl: true,
    label: "Ctrl+I",
    description: "Inventory Dashboard",
    group: "INVENTORY",
  },
  {
    id: "new_item",
    key: "n",
    ctrl: true,
    label: "Ctrl+N",
    description: "New Stock Item",
    group: "INVENTORY",
  },
  {
    id: "edit_item",
    key: "e",
    ctrl: true,
    label: "Ctrl+E",
    description: "Edit Item",
    group: "INVENTORY",
  },
  {
    id: "delete_item",
    key: "d",
    ctrl: true,
    label: "Ctrl+D",
    description: "Delete Item",
    group: "INVENTORY",
  },
  {
    id: "stock_transfer",
    key: "t",
    ctrl: true,
    label: "Ctrl+T",
    description: "Stock Transfer",
    group: "INVENTORY",
  },
  {
    id: "stock_report",
    key: "r",
    ctrl: true,
    label: "Ctrl+R",
    description: "Stock Report",
    group: "INVENTORY",
  },

  // ── Billing ──────────────────────────────────────────────────────
  {
    id: "new_invoice",
    key: "b",
    ctrl: true,
    label: "Ctrl+B",
    description: "New Invoice",
    group: "BILLING",
  },
  {
    id: "print_invoice",
    key: "p",
    ctrl: true,
    label: "Ctrl+P",
    description: "Print Invoice",
    group: "BILLING",
  },
  {
    id: "pdf_invoice",
    key: "p",
    ctrl: true,
    shift: true,
    label: "Ctrl+Shift+P",
    description: "Download PDF",
    group: "BILLING",
  },
  {
    id: "email_invoice",
    key: "m",
    ctrl: true,
    label: "Ctrl+M",
    description: "Email Invoice",
    group: "BILLING",
  },

  // ── Customer ─────────────────────────────────────────────────────
  {
    id: "new_customer",
    key: "c",
    ctrl: true,
    label: "Ctrl+C",
    description: "New Customer",
    group: "CUSTOMER",
  },
  {
    id: "customer_ledger",
    key: "c",
    ctrl: true,
    shift: true,
    label: "Ctrl+Shift+C",
    description: "Customer Ledger",
    group: "CUSTOMER",
  },

  // ── Supplier ─────────────────────────────────────────────────────
  {
    id: "new_supplier",
    key: "s",
    ctrl: true,
    label: "Ctrl+S",
    description: "New Supplier",
    group: "SUPPLIER",
  },
  {
    id: "supplier_ledger",
    key: "s",
    ctrl: true,
    shift: true,
    label: "Ctrl+Shift+S",
    description: "Supplier Ledger",
    group: "SUPPLIER",
  },

  // ── Reports ──────────────────────────────────────────────────────
  {
    id: "balance_sheet",
    key: "b",
    alt: true,
    label: "Alt+B",
    description: "Balance Sheet",
    group: "REPORTS",
  },
  {
    id: "profit_loss",
    key: "p",
    alt: true,
    label: "Alt+P",
    description: "Profit & Loss",
    group: "REPORTS",
  },
  {
    id: "trial_balance",
    key: "t",
    alt: true,
    label: "Alt+T",
    description: "Trial Balance",
    group: "REPORTS",
  },
  {
    id: "cash_flow",
    key: "c",
    alt: true,
    label: "Alt+C",
    description: "Cash Flow",
    group: "REPORTS",
  },
  {
    id: "stock_summary",
    key: "r",
    alt: true,
    label: "Alt+R",
    description: "Stock Summary",
    group: "REPORTS",
  },
  {
    id: "gst_report",
    key: "x",
    alt: true,
    label: "Alt+X",
    description: "GST Report",
    group: "REPORTS",
  },

  // ── Navigation ───────────────────────────────────────────────────
  {
    id: "search",
    key: "f",
    ctrl: true,
    label: "Ctrl+F",
    description: "Search",
    group: "NAVIGATE",
  },
  {
    id: "global_search",
    key: "f",
    ctrl: true,
    shift: true,
    label: "Ctrl+Shift+F",
    description: "Global Search",
    group: "NAVIGATE",
  },
];

// Helper: get shortcut label by id
export const getShortcutLabel = (id) =>
  SHORTCUTS.find((s) => s.id === id)?.label || "";
